apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: mariadb
        image: mariadb:lts-ubi9
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-storage
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secrets
                key: DB_PASSWORD
      volumes:
        - name: mariadb-storage
          # mount /data/foo, but only if that directory already exists
          persistentVolumeClaim:
            claimName: mariadb-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: NodePort
  selector:
    app: traccar
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30302
